GET http://localhost:3000/

###
GET http://localhost:3000/user

###
GET http://localhost:3000/user/email/s346317@studenti.polito.it/password/346317

###
POST http://localhost:3000/user
Content-Type: application/json

{ "username": "Andrea",
  "email" : "s346317@studenti.polito.it",
  "password" : "346317"}


###
POST http://localhost:3000/user
Content-Type: application/json

{ "username": "Tommaso",
  "email" : "s346565@studenti.polito.it",
  "password" : "346565"}

###
POST http://localhost:3000/user
Content-Type: application/json

{ "username": "Sam",
  "email" : "s293382@studenti.polito.it",
  "password" : "293382"}

### POST WITH CHECK starter
POST http://localhost:3000/user/check
Content-Type: application/json

{ "username": "Sam",
  "email" : "s293382@studenti.polito.it",
  "password" : "293382"}

### POST WITH CHECK user
POST http://localhost:3000/user/check
Content-Type: application/json

{ "username": "Sam",
  "email" : "bananita@studenti.polito.it",
  "password" : "293382"}
### POST WITH CHECK mail
POST http://localhost:3000/user/check
Content-Type: application/json

{ "username": "bananita",
  "email" : "s293382@studenti.polito.it",
  "password" : "293382"}



### DELETE
DELETE  http://localhost:3000/user
Content-Type: application/json

{ "username": "Sam",
  "email" : "bananita@studenti.polito.it",
  "password" : "293382"}


###

POST http://localhost:3000/user
Content-Type: application/json

{ "name": "Jim", "id":99 }

### 

PUT http://localhost:3000/users?name=Fulvio


###

GET http://localhost:3000/user/20/name


###
GET http://localhost:3000/user