GET http://localhost:3000/

###
GET http://localhost:3000/user

###
GET http://localhost:3000/user/email/s346317@studenti.polito.it/password/346317

###
POST http://localhost:3000/user
Content-Type: application/json

{ "username": "Andrea",
  "email" : "s346317@studenti.polito.it",
  "password" : "346317"}


###
POST http://localhost:3000/user
Content-Type: application/json

{ "username": "Tommaso",
  "email" : "s346565@studenti.polito.it",
  "password" : "346565"}

###
POST http://localhost:3000/user
Content-Type: application/json

{ "username": "Sam",
  "email" : "s293382@studenti.polito.it",
  "password" : "293382"}

### POST WITH CHECK starter
POST http://localhost:3000/user/check
Content-Type: application/json

{ "username": "Sam",
  "email" : "test@mail.com",
  "password" : "password123"}

### POST WITH CHECK user
POST http://localhost:3000/user/check
Content-Type: application/json

{ "username": "Sam",
  "email" : "bananita@studenti.polito.it",
  "password" : "293382"}
### POST WITH CHECK mail
POST http://localhost:3000/user/check
Content-Type: application/json

{ "username": "bananita",
  "email" : "s293382@studenti.polito.it",
  "password" : "293382"}



### DELETE
DELETE  http://localhost:3000/user
Content-Type: application/json

{ "username": "Sam",
  "email" : "bananita@studenti.polito.it",
  "password" : "293382"}


### AUTH by email

GET http://localhost:3000/user/authenticate?email=test@mail.com&password=password123

### AUTH by username

GET http://localhost:3000/user/authenticate?username=Sam&password=password123

### AUTH by email WRONG 

GET http://localhost:3000/user/authenticate?email=test@mail.com&password=password124

### AUTH by username WRONG

GET http://localhost:3000/user/authenticate?username=Sam&password=password124
###



### 

GET http://localhost:3000/bowls


###
GET http://localhost:3000/user